FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime

WORKDIR /usr/local/app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        python3.8 \
        python3.8-venv \
        python3-pip \
        unzip \
        sox \
        ffmpeg

SHELL ["/bin/bash", "-c"]

COPY . .

RUN chmod +x entrypoint-api.sh

CMD ["./entrypoint-api.sh"]
